# These settings are synced to GitHub by https://probot.github.io/apps/settings/
# Requires https://github.com/apps/settings to be configured for the organization
# The documentation for these settings are in the settings repository and generally map onto the github rest api

# By being in the .github repository these apply globally to the whole organization
# These settings only apply at repository creation, the individual repositories can create/override their own rules

repository:
  private: true
  has_issues: true
  has_projects: true
  has_wiki: false
  has_downloads: true
  default_branch: main
  # only allow regular merge and squashes
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: false
  delete_branch_on_merge: false
  enable_automated_security_fixes: true
  enable_vulnerability_alerts: true

labels:
  # unused for now

milestones:
  # unused for now

collaborators:
  # unused for now

teams:
  # unused for now

branches:
  # one required reviewer
  - name: main
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
      required_status_checks: null
      enforce_admins: null
      required_linear_history: false
      restrictions: null
  # no required reviewers
  - name: UAT
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 0
        dismiss_stale_reviews: true
      required_status_checks: null
      enforce_admins: null
      required_linear_history: false
      restrictions: null
  # no required reviewers, requires linear history to force squash merging
  - name: E2E
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 0
        dismiss_stale_reviews: true
      required_status_checks: null
      enforce_admins: null
      required_linear_history: true
      restrictions: null